name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: ${{ matrix.downgrade && 'Downgrade / ' || '' }}Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.6'
          - '1'
          - 'nightly'
        os:
          - ubuntu-latest
        arch:
          - x64
        downgrade:
          - false
        include:
          - version: '1'
            os: macOS-latest
            arch: x64
            downgrade: false
          - version: '1'
            os: windows-latest
            arch: x64
            downgrade: false
          - version: '1'
            os: ubuntu-latest
            arch: x64
            downgrade: true
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1
      - uses: cjdoris/julia-downgrade-compat-action@v1
        with:
          skip: LinearAlgebra,Markdown,Printf,Random,Statistics
        if: ${{ matrix.downgrade }}
        name: Downgrade dependencies to oldest supported versions
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        with:
          coverage: ${{ matrix.version == '1' && matrix.os == 'ubuntu-latest' }}
      - uses: julia-actions/julia-processcoverage@v1
        if: matrix.version == '1' && matrix.os == 'ubuntu-latest'
      - uses: codecov/codecov-action@v4
        if: matrix.version == '1' && matrix.os == 'ubuntu-latest'
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: lcov.info
          fail_ci_if_error: true
      - uses: coverallsapp/github-action@v2
        if: matrix.version == '1' && matrix.os == 'ubuntu-latest'
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            path-to-lcov: ./lcov.info
